// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsPsReplaceAccents
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsPsReplaceAccents.83246dfa-cdd6-4a6e-a093-81c8f9ead99e";
        public const string Name = "Replace Accents";
        public const string Description = @"Remove accents/diacritics from text to generate clean text through Unicode normalization and custom character mappings.";
        public const string Language = "en-US";
        public const string Version = "0.0.3";
        public const string Author = "Playful Sparkle";
        public const string Tags = "ascii, diacritics, accent, letter, alphabet, remove, replace, playfulsparkle, visualstudio, extension";
        public const bool IsPreview = false;
    }
}
