// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsPsReplaceAccents
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsPsReplaceAccentsString = "8f2ecea4-4d8d-4c98-accd-a0c6f83f9fe7";
        public static Guid VsPsReplaceAccents = new Guid(VsPsReplaceAccentsString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VsMenuGroup = 0x0001;
        public const int VsReplaceAccents = 0x0100;
    }
}
